/**
 * @module encoding
 */
/*
 * We use the first five bits in the info flag for determining the type of the struct.
 *
 * 0: GC
 * 1: Item with Deleted content
 * 2: Item with JSON content
 * 3: Item with Binary content
 * 4: Item with String content
 * 5: Item with Embed content (for richtext content)
 * 6: Item with Format content (a formatting marker for richtext content)
 * 7: Item with Type
 */

import * as encoding from 'lib0/encoding'
import * as decoding from 'lib0/decoding'
import * as map from 'lib0/map'
import * as math from 'lib0/math'
import * as array from 'lib0/array'

import { getStateVector, StructStore } from './StructStore.js'
import { findIndexSS, getItemCleanStart, getItemCleanEnd } from './transaction-helpers.js'
import { createIdSet, IdRange, readAndApplyDeleteSet, readIdSet, mergeIdSets, writeIdSet } from './ids.js'
import { compareIDs, createID, ID } from './ID.js'
import { UpdateDecoderV1, UpdateDecoderV2, IdSetDecoderV1 } from './UpdateDecoder.js'
import { UpdateEncoderV1, UpdateEncoderV2, IdSetEncoderV1, IdSetEncoderV2 } from './UpdateEncoder.js'
import { convertUpdateFormatV2ToV1, LazyStructReader, LazyStructWriter, writeStructToLazyStructWriter, finishLazyStructWriting } from './updates.js'
import { readBlockSet, writeBlockSet } from './BlockSet.js'
import { Skip } from '../structs/Skip.js'
import { ContentType, Item } from '../structs/Item.js'
import { GC } from '../structs/GC.js'
import { CausalHole, normalizeCausalHoleParent, sameCausalHoleMetadata, sameCausalHoleParent } from '../structs/CausalHole.js'
import { Doc } from './Doc.js'
import { writeStructs } from './encoding-helpers.js'

/**
 * @param {UpdateEncoderV1 | UpdateEncoderV2} encoder
 * @param {StructStore} store
 * @param {Map<number,number>} _sm
 *
 * @private
 * @function
 */
export const writeClientsStructs = (encoder, store, _sm) => {
  // we filter all valid _sm entries into sm
  const sm = new Map()
  _sm.forEach((clock, client) => {
    // only write if new structs are available
    if (store.getClock(client) > clock) {
      sm.set(client, clock)
    }
  })
  getStateVector(store).forEach((_clock, client) => {
    if (!_sm.has(client)) {
      sm.set(client, 0)
    }
  })
  // write # states that were updated
  encoding.writeVarUint(encoder.restEncoder, sm.size)
  // Write items with higher client ids first
  // This heavily improves the conflict algorithm.
  array.from(sm.entries()).sort((a, b) => b[0] - a[0]).forEach(([client, clock]) => {
    const structs = /** @type {Array<GC|Item|Skip|CausalHole>} */ (store.clients.get(client))
    const lastStruct = structs[structs.length - 1]
    writeStructs(encoder, structs, client, [new IdRange(clock, lastStruct.id.clock + lastStruct.length - clock)])
  })
}

/**
 * Resume computing structs generated by struct readers.
 *
 * While there is something to do, we integrate structs in this order
 * 1. top element on stack, if stack is not empty
 * 2. next element from current struct reader (if empty, use next struct reader)
 *
 * If struct causally depends on another struct (ref.missing), we put next reader of
 * `ref.id.client` on top of stack.
 *
 * At some point we find a struct that has no causal dependencies,
 * then we start emptying the stack.
 *
 * It is not possible to have circles: i.e. struct1 (from client1) depends on struct2 (from client2)
 * depends on struct3 (from client1). Therefore the max stack size is equal to `structReaders.length`.
 *
 * This method is implemented in a way so that we can resume computation if this update
 * causally depends on another update.
 *
 * @param {Transaction} transaction
 * @param {StructStore} store
 * @param {BlockSet} clientsStructRefs
 * @return { null | { update: Uint8Array<ArrayBuffer>, missing: Map<number,number> } }
 *
 * @private
 * @function
 */
const integrateStructs = (transaction, store, clientsStructRefs) => {
  /**
   * @type {Array<Item | GC | Skip | CausalHole>}
   */
  const stack = []
  // sort them so that we take the higher id first, in case of conflicts the lower id will probably not conflict with the id from the higher user.
  let clientsStructRefsIds = array.from(clientsStructRefs.clients.keys()).sort((a, b) => a - b)
  if (clientsStructRefsIds.length === 0) {
    return null
  }
  const getNextStructTarget = () => {
    if (clientsStructRefsIds.length === 0) {
      return null
    }
    let nextStructsTarget = /** @type {{i:number,refs:Array<GC|Item>}} */ (clientsStructRefs.clients.get(clientsStructRefsIds[clientsStructRefsIds.length - 1]))
    while (nextStructsTarget.refs.length === nextStructsTarget.i) {
      clientsStructRefsIds.pop()
      if (clientsStructRefsIds.length > 0) {
        nextStructsTarget = /** @type {{i:number,refs:Array<GC|Item>}} */ (clientsStructRefs.clients.get(clientsStructRefsIds[clientsStructRefsIds.length - 1]))
      } else {
        return null
      }
    }
    return nextStructsTarget
  }
  let curStructsTarget = getNextStructTarget()
  if (curStructsTarget === null) {
    return null
  }

  /**
   * @type {StructStore}
   */
  const restStructs = new StructStore()
  const missingSV = new Map()
  /**
   * @param {number} client
   * @param {number} clock
   */
  const updateMissingSv = (client, clock) => {
    const mclock = missingSV.get(client)
    if (mclock == null || mclock > clock) {
      missingSV.set(client, clock)
    }
  }
  /**
   * @type {GC|Item|Skip|CausalHole}
   */
  let stackHead = /** @type {any} */ (curStructsTarget).refs[/** @type {any} */ (curStructsTarget).i++]
  // caching the state because it is used very often
  const state = new Map()

  // // caching the state because it is used very often
  // const currentInsertSet = createIdSet()
  // clientsStructRefsIds.forEach(clientId => {
  //   currentInsertSet.clients.set(clientid, new IdRanges(_createInsertSliceFromStructs(store.clients.get(clientId) ?? [], false)))
  // })

  const addStackToRestSS = () => {
    for (const item of stack) {
      const client = item.id.client
      const inapplicableItems = clientsStructRefs.clients.get(client)
      if (inapplicableItems) {
        // decrement because we weren't able to apply previous operation
        inapplicableItems.i--
        restStructs.clients.set(client, /** @type {Array<GC|Item|Skip>} */ (/** @type {unknown} */ (inapplicableItems.refs.slice(inapplicableItems.i))))
        clientsStructRefs.clients.delete(client)
        inapplicableItems.i = 0
        inapplicableItems.refs = []
      } else {
        // item was the last item on clientsStructRefs and the field was already cleared. Add item to restStructs and continue
        restStructs.clients.set(client, /** @type {Array<GC|Item|Skip>} */ (/** @type {unknown} */ ([item])))
      }
      // remove client from clientsStructRefsIds to prevent users from applying the same update again
      clientsStructRefsIds = clientsStructRefsIds.filter(c => c !== client)
    }
    stack.length = 0
  }

  // iterate over all struct readers until we are done
  while (true) {
    if (stackHead.constructor !== Skip) {
      const localClock = map.setIfUndefined(state, stackHead.id.client, () => store.getClock(stackHead.id.client))
      const offset = localClock - stackHead.id.clock
      const missing = getMissing(/** @type {any} */ (stackHead), transaction, store)
      if (missing !== null) {
        stack.push(stackHead)
        // get the struct reader that has the missing struct
        /**
         * @type {{ refs: Array<GC|Item|Skip|CausalHole>, i: number }}
         */
        const structRefs = clientsStructRefs.clients.get(/** @type {number} */ (missing)) || { refs: [], i: 0 }
        if (structRefs.refs.length === structRefs.i || missing === stackHead.id.client || stack.some(s => s.id.client === missing)) { // @todo this could be optimized!
          // This update message causally depends on another update message that doesn't exist yet
          updateMissingSv(/** @type {number} */ (missing), store.getClock(missing))
          addStackToRestSS()
        } else {
          stackHead = structRefs.refs[structRefs.i++]
          continue
        }
      } else {
        // all fine, apply the stackhead
        // but first add a skip to structs if necessary
        if (offset < 0) {
          const skip = new Skip(createID(stackHead.id.client, localClock), -offset)
          skip.integrate(transaction, 0)
        }
        stackHead.integrate(transaction, 0)
        state.set(stackHead.id.client, math.max(stackHead.id.clock + stackHead.length, localClock))
      }
    }
    // iterate to next stackHead
    if (stack.length > 0) {
      stackHead = /** @type {GC|Item|CausalHole} */ (stack.pop())
    } else if (curStructsTarget !== null && curStructsTarget.i < curStructsTarget.refs.length) {
      stackHead = /** @type {GC|Item|CausalHole} */ (curStructsTarget.refs[curStructsTarget.i++])
    } else {
      curStructsTarget = getNextStructTarget()
      if (curStructsTarget === null) {
        // we are done!
        break
      } else {
        stackHead = /** @type {GC|Item|CausalHole} */ (curStructsTarget.refs[curStructsTarget.i++])
      }
    }
  }
  if (restStructs.clients.size > 0) {
    const encoder = new UpdateEncoderV2()
    writeClientsStructs(encoder, restStructs, new Map())
    // write empty deleteset
    // writeDeleteSet(encoder, new DeleteSet())
    encoding.writeVarUint(encoder.restEncoder, 0) // => no need for an extra function call, just write 0 deletes
    return { missing: missingSV, update: encoder.toUint8Array() }
  }
  return null
}

/**
 * Read and apply a document update.
 *
 * This function has the same effect as `applyUpdate` but accepts a decoder.
 *
 * @param {decoding.Decoder} decoder
 * @param {Doc} ydoc
 * @param {any} [transactionOrigin] This will be stored on `transaction.origin` and `.on('update', (update, origin))`
 * @param {UpdateDecoderV1 | UpdateDecoderV2} [structDecoder]
 *
 * @function
 */
export const readUpdateV2 = (decoder, ydoc, transactionOrigin, structDecoder = new UpdateDecoderV2(decoder)) =>
  ydoc.transact(transaction => {
    // force that transaction.local is set to non-local
    transaction.local = false
    let retry = false
    const doc = transaction.doc
    const store = doc.store
    // let start = performance.now()
    const ss = readBlockSet(structDecoder)
    const ranges = array.from(ss.clients.values())
    const hasIncomingHoles = ranges.some(range => range.refs.some(struct => struct.constructor === CausalHole))
    const hasSparseCausality = hasIncomingHoles || (!store.causalHoles.isEmpty() && ranges.some(range => range.refs.some(struct =>
      struct.constructor === Item && (
        (struct.origin !== null && store.causalHoles.hasId(struct.origin)) ||
        (struct.rightOrigin !== null && store.causalHoles.hasId(struct.rightOrigin))
      )
    )))
    const sparseDeleteSet = hasSparseCausality ? readIdSet(structDecoder) : null
    validateCausalHoleEnvelope(ss, store)
    splitIncomingItemsAtCausalHoleConsumers(ss, store)
    const knownState = createIdSet()
    ss.clients.forEach((_, client) => {
      const storeStructs = store.clients.get(client)
      if (storeStructs) {
        const last = storeStructs[storeStructs.length - 1]
        knownState.add(client, 0, last.id.clock + last.length)
        // remove known items from ss
        store.skips.clients.get(client)?.getIds().forEach(idrange => {
          knownState.delete(client, idrange.clock, idrange.len)
        })
        store.causalHoles.clients.get(client)?.getIds().forEach(idrange => {
          knownState.delete(client, idrange.clock, idrange.len)
        })
      }
    })
    // remove known items from ss
    ss.exclude(knownState)
    // console.log('time to read structs: ', performance.now() - start) // @todo remove
    // start = performance.now()
    // console.log('time to merge: ', performance.now() - start) // @todo remove
    // start = performance.now()
    const restStructs = integrateStructs(transaction, store, ss)
    const pending = store.pendingStructs
    if (pending) {
      // check if we can apply something
      for (const [client, clock] of pending.missing) {
        if (ss.clients.has(client) || clock < store.getClock(client)) {
          retry = true
          break
        }
      }
      if (restStructs) {
        // merge restStructs into store.pending
        for (const [client, clock] of restStructs.missing) {
          const mclock = pending.missing.get(client)
          if (mclock == null || mclock > clock) {
            pending.missing.set(client, clock)
          }
        }
        pending.update = mergeUpdatesV2([pending.update, restStructs.update])
      }
    } else {
      store.pendingStructs = restStructs
    }
    // console.log('time to integrate: ', performance.now() - start) // @todo remove
    // start = performance.now()
    const dsRest = sparseDeleteSet === null
      ? readAndApplyDeleteSet(structDecoder, transaction, store)
      : applyDecodedDeleteSet(sparseDeleteSet, transaction, store)
    if (store.pendingDs) {
      // @todo we could make a lower-bound state-vector check as we do above
      const pendingDSUpdate = new UpdateDecoderV2(decoding.createDecoder(store.pendingDs))
      decoding.readVarUint(pendingDSUpdate.restDecoder) // read 0 structs, because we only encode deletes in pendingdsupdate
      const dsRest2 = readAndApplyDeleteSet(pendingDSUpdate, transaction, store)
      if (dsRest && dsRest2) {
        // case 1: ds1 != null && ds2 != null
        store.pendingDs = mergeUpdatesV2([dsRest, dsRest2])
      } else {
        // case 2: ds1 != null
        // case 3: ds2 != null
        // case 4: ds1 == null && ds2 == null
        store.pendingDs = dsRest || dsRest2
      }
    } else {
      // Either dsRest == null && pendingDs == null OR dsRest != null
      store.pendingDs = dsRest
    }
    // console.log('time to cleanup: ', performance.now() - start) // @todo remove
    // start = performance.now()

    // console.log('time to resume delete readers: ', performance.now() - start) // @todo remove
    // start = performance.now()
    if (retry) {
      const update = /** @type {{update: Uint8Array}} */ (store.pendingStructs).update
      store.pendingStructs = null
      applyUpdateV2(transaction.doc, update)
    }
  }, transactionOrigin, false)

/**
 * @param {IdSet} deleteSet
 * @param {Transaction} transaction
 * @param {StructStore} store
 */
const applyDecodedDeleteSet = (deleteSet, transaction, store) => {
  const encoder = new UpdateEncoderV2()
  encoding.writeVarUint(encoder.restEncoder, 0)
  writeIdSet(encoder, deleteSet)
  const decoder = new UpdateDecoderV2(decoding.createDecoder(encoder.toUint8Array()))
  decoding.readVarUint(decoder.restDecoder)
  return readAndApplyDeleteSet(decoder, transaction, store)
}

/**
 * @param {BlockSet} blockSet
 * @param {StructStore} store
 */
const validateCausalHoleEnvelope = (blockSet, store) => {
  /** @type {Array<CausalHole>} */
  const incomingHoles = []
  /** @type {Array<Item>} */
  const incomingItems = []
  blockSet.clients.forEach(range => {
    range.refs.forEach(struct => {
      if (struct.constructor === CausalHole) incomingHoles.push(/** @type {CausalHole} */ (struct))
      if (struct.constructor === Item) incomingItems.push(/** @type {Item} */ (struct))
    })
  })
  if (incomingHoles.length === 0 && store.causalHoles.isEmpty()) return
  /**
   * @param {ID} id
   */
  const incomingAt = id => {
    const refs = blockSet.clients.get(id.client)?.refs
    if (refs === undefined || refs.length === 0 || id.clock < refs[0].id.clock) return null
    const last = refs[refs.length - 1]
    if (id.clock >= last.id.clock + last.length) return null
    let left = 0
    let right = refs.length - 1
    while (left <= right) {
      const middle = (left + right) >>> 1
      const struct = refs[middle]
      if (id.clock < struct.id.clock) right = middle - 1
      else if (id.clock >= struct.id.clock + struct.length) left = middle + 1
      else return struct
    }
    return null
  }
  /**
   * @param {ID} id
   */
  const resolve = id => {
    const incoming = incomingAt(id)
    const existing = store.getStruct(id)
    if (incoming?.constructor === Item) return incoming
    if (existing?.constructor === Item) return existing
    if (incoming?.constructor === CausalHole) return incoming
    if (existing?.constructor === CausalHole) return existing
    return null
  }
  /**
   * @param {CausalHole} hole
   */
  const coveredByRealStore = hole => {
    let clock = hole.id.clock
    const end = clock + hole.length
    while (clock < end) {
      const struct = store.getStruct(createID(hole.id.client, clock))
      if (struct?.constructor !== Item) return false
      clock = Math.min(end, struct.id.clock + struct.length)
    }
    return true
  }
  for (const hole of incomingHoles) {
    if (coveredByRealStore(hole)) continue
    const existingStructs = store.clients.get(hole.id.client) ?? []
    if (existingStructs.length === 0 || hole.id.clock >= store.getClock(hole.id.client)) continue
    let index = findIndexSS(existingStructs, Math.max(hole.id.clock, existingStructs[0].id.clock))
    for (let existing = existingStructs[index]; existing !== undefined && existing.id.clock < hole.id.clock + hole.length; existing = existingStructs[++index]) {
      const start = Math.max(hole.id.clock, existing.id.clock)
      const end = Math.min(hole.id.clock + hole.length, existing.id.clock + existing.length)
      if (start >= end || existing.constructor !== CausalHole) continue
      if (!sameCausalHoleMetadata(hole.slice(start, end - start), /** @type {CausalHole} */ (existing).slice(start, end - start))) {
        throw new Error('Conflicting causal hole metadata')
      }
    }
  }

  /** @param {CausalHole} hole */
  const validateStructuralParent = hole => {
    if (typeof hole.parent === 'string') return
    const parent = resolve(hole.parent)
    if (parent?.constructor !== Item || !(/** @type {Item} */ (parent).content instanceof ContentType)) {
      throw new Error('Causal hole parent is not a materialized type')
    }
  }

  /** @type {Array<CausalHole>} */
  const roots = incomingHoles.filter(hole => !coveredByRealStore(hole))
  for (const item of incomingItems) {
    for (const anchor of [item.origin, item.rightOrigin]) {
      if (anchor === null) continue
      const dependency = resolve(anchor)
      if (dependency?.constructor === CausalHole) roots.push(/** @type {CausalHole} */ (dependency))
    }
  }
  if (roots.length === 0) return

  /** @type {Map<CausalHole,0|1|2>} */
  const colors = new Map()
  const reachable = new Set()
  for (const root of roots) {
    if (colors.get(root) === 2) continue
    /** @type {Array<{hole:CausalHole,next:number}>} */
    const stack = [{ hole: root, next: 0 }]
    colors.set(root, 1)
    while (stack.length > 0) {
      const frame = stack[stack.length - 1]
      reachable.add(frame.hole)
      if (frame.next === 0) validateStructuralParent(frame.hole)
      const anchors = [frame.hole.origin, frame.hole.rightOrigin]
      if (frame.next >= anchors.length) {
        colors.set(frame.hole, 2)
        stack.pop()
        continue
      }
      const anchor = anchors[frame.next++]
      if (anchor === null) continue
      const dependency = resolve(anchor)
      if (dependency === null || dependency.constructor === Skip) throw new Error('Missing causal hole anchor')
      if (dependency.constructor !== CausalHole) continue
      const next = /** @type {CausalHole} */ (dependency)
      const color = colors.get(next) ?? 0
      if (color === 1) throw new Error('Cyclic causal hole metadata')
      if (color === 0) {
        colors.set(next, 1)
        stack.push({ hole: next, next: 0 })
      }
    }
  }

  /** @typedef {{parent:ID|string,parentSub:string|null}} ParentMetadata */
  /** @type {Map<Item|CausalHole,ParentMetadata>} */
  const parentMemo = new Map()
  /** @param {Item|CausalHole} start */
  const getParentMetadata = start => {
    const cached = parentMemo.get(start)
    if (cached !== undefined) return cached
    /** @type {Array<Item|CausalHole>} */
    const path = []
    const seen = new Set()
    /** @type {Item|CausalHole} */
    let current = start
    /** @type {ParentMetadata|null} */
    let metadata = null
    while (metadata === null) {
      const known = parentMemo.get(current)
      if (known !== undefined) {
        metadata = known
        break
      }
      if (seen.has(current)) throw new Error('Cyclic sparse parent metadata')
      seen.add(current)
      path.push(current)
      if (current.constructor === CausalHole) {
        const hole = /** @type {CausalHole} */ (current)
        metadata = { parent: hole.parent, parentSub: hole.parentSub }
        break
      }
      const item = /** @type {Item} */ (current)
      if (item.parent !== null) {
        metadata = { parent: normalizeCausalHoleParent(item.parent), parentSub: item.parentSub }
        break
      }
      const anchor = item.origin ?? item.rightOrigin
      if (anchor === null) throw new Error('Sparse item parent cannot be inferred')
      const dependency = resolve(anchor)
      if (dependency?.constructor !== Item && dependency?.constructor !== CausalHole) throw new Error('Sparse item parent cannot be inferred')
      current = /** @type {Item|CausalHole} */ (dependency)
    }
    for (const struct of path) parentMemo.set(struct, metadata)
    return metadata
  }
  /** @param {ParentMetadata} actual @param {ParentMetadata} expected */
  const assertParentMetadata = (actual, expected) => {
    if (!sameCausalHoleParent(actual.parent, expected.parent) || actual.parentSub !== expected.parentSub) {
      throw new Error('Conflicting causal hole parent metadata')
    }
  }

  /** @type {Map<CausalHole,Item|null>} */
  const leftTerminal = new Map()
  /** @type {Map<CausalHole,Item|null>} */
  const rightTerminal = new Map()
  /** @param {CausalHole} start @param {boolean} left */
  const getTerminal = (start, left) => {
    const memo = left ? leftTerminal : rightTerminal
    const cached = memo.get(start)
    if (cached !== undefined || memo.has(start)) return cached ?? null
    /** @type {Array<CausalHole>} */
    const path = []
    let current = start
    /** @type {Item|null} */
    let terminal = null
    while (true) {
      if (memo.has(current)) {
        terminal = memo.get(current) ?? null
        break
      }
      path.push(current)
      const anchor = left ? current.origin : current.rightOrigin
      if (anchor === null) break
      const dependency = resolve(anchor)
      if (dependency?.constructor === Item) {
        terminal = /** @type {Item} */ (dependency)
        break
      }
      if (dependency?.constructor !== CausalHole) throw new Error('Missing causal hole anchor')
      current = /** @type {CausalHole} */ (dependency)
    }
    for (const hole of path) memo.set(hole, terminal)
    return terminal
  }

  reachable.forEach(hole => {
    const expected = { parent: hole.parent, parentSub: hole.parentSub }
    const left = getTerminal(hole, true)
    const right = getTerminal(hole, false)
    if (left !== null) assertParentMetadata(getParentMetadata(left), expected)
    if (right !== null) assertParentMetadata(getParentMetadata(right), expected)
  })

  for (const item of incomingItems) {
    const dependencies = [item.origin, item.rightOrigin]
      .filter(anchor => anchor !== null)
      .map(anchor => resolve(/** @type {ID} */ (anchor)))
    const hole = dependencies.find(dependency => dependency?.constructor === CausalHole)
    if (hole?.constructor !== CausalHole) continue
    const expected = getParentMetadata(/** @type {CausalHole} */ (hole))
    assertParentMetadata(getParentMetadata(item), expected)
    for (const dependency of dependencies) {
      if (dependency?.constructor === Item || dependency?.constructor === CausalHole) {
        assertParentMetadata(getParentMetadata(/** @type {Item|CausalHole} */ (dependency)), expected)
      }
    }
  }
}

/**
 * @param {BlockSet} blockSet
 * @param {StructStore} store
 */
const splitIncomingItemsAtCausalHoleConsumers = (blockSet, store) => {
  if (store.causalHoleConsumers.size === 0) return
  blockSet.clients.forEach((range, client) => {
    for (let index = 0; index < range.refs.length; index++) {
      const struct = range.refs[index]
      if (struct.constructor !== Item || !store.causalHoles.intersects(client, struct.id.clock, struct.length)) continue
      const start = struct.id.clock
      const end = start + struct.length
      const boundaries = Array.from(new Set(store.getCausalHoleConsumers(client, start, struct.length)
        .map(consumer => consumer.side === 'origin' ? consumer.clock + 1 : consumer.clock)
        .filter(clock => start < clock && clock < end)))
        .sort((left, right) => left - right)
      let current = /** @type {Item} */ (struct)
      for (const clock of boundaries) {
        const right = current.split(null, clock - current.id.clock)
        range.refs.splice(++index, 0, right)
        current = right
      }
    }
  })
}

/**
 * Read and apply a document update.
 *
 * This function has the same effect as `applyUpdate` but accepts a decoder.
 *
 * @param {decoding.Decoder} decoder
 * @param {Doc} ydoc
 * @param {any} [transactionOrigin] This will be stored on `transaction.origin` and `.on('update', (update, origin))`
 *
 * @function
 */
export const readUpdate = (decoder, ydoc, transactionOrigin) => readUpdateV2(decoder, ydoc, transactionOrigin, new UpdateDecoderV1(decoder))

/**
 * Apply a document update created by, for example, `y.on('update', update => ..)` or `update = encodeStateAsUpdate()`.
 *
 * This function has the same effect as `readUpdate` but accepts an Uint8Array instead of a Decoder.
 *
 * @param {Doc} ydoc
 * @param {Uint8Array} update
 * @param {any} [transactionOrigin] This will be stored on `transaction.origin` and `.on('update', (update, origin))`
 * @param {typeof UpdateDecoderV1 | typeof UpdateDecoderV2} [YDecoder]
 *
 * @function
 */
export const applyUpdateV2 = (ydoc, update, transactionOrigin, YDecoder = UpdateDecoderV2) => {
  const decoder = decoding.createDecoder(update)
  readUpdateV2(decoder, ydoc, transactionOrigin, new YDecoder(decoder))
}

/**
 * Apply a document update created by, for example, `y.on('update', update => ..)` or `update = encodeStateAsUpdate()`.
 *
 * This function has the same effect as `readUpdate` but accepts an Uint8Array instead of a Decoder.
 *
 * @param {Doc} ydoc
 * @param {Uint8Array} update
 * @param {any} [transactionOrigin] This will be stored on `transaction.origin` and `.on('update', (update, origin))`
 *
 * @function
 */
export const applyUpdate = (ydoc, update, transactionOrigin) => applyUpdateV2(ydoc, update, transactionOrigin, UpdateDecoderV1)

/**
 * Write all the document as a single update message. If you specify the state of the remote client (`targetStateVector`) it will
 * only write the operations that are missing.
 *
 * @param {UpdateEncoderV1 | UpdateEncoderV2} encoder
 * @param {Doc} doc
 * @param {Map<number,number>} [targetStateVector] The state of the target that receives the update. Leave empty to write all known structs
 *
 * @function
 */
export const writeStateAsUpdate = (encoder, doc, targetStateVector = new Map()) => {
  writeClientsStructs(encoder, doc.store, targetStateVector)
  writeIdSet(encoder, doc.store.ds)
}

/**
 * Write all the document as a single update message that can be applied on the remote document. If you specify the state of the remote client (`targetState`) it will
 * only write the operations that are missing.
 *
 * Use `writeStateAsUpdate` instead if you are working with lib0/encoding.js#Encoder
 *
 * @param {Doc} doc
 * @param {Uint8Array} [encodedTargetStateVector] The state of the target that receives the update. Leave empty to write all known structs
 * @param {UpdateEncoderV1 | UpdateEncoderV2} [encoder]
 * @return {Uint8Array<ArrayBuffer>}
 *
 * @function
 */
export const encodeStateAsUpdateV2 = (doc, encodedTargetStateVector = new Uint8Array([0]), encoder = new UpdateEncoderV2()) => {
  const targetStateVector = decodeStateVector(encodedTargetStateVector)
  writeStateAsUpdate(encoder, doc, targetStateVector)
  const updates = [encoder.toUint8Array()]
  // also add the pending updates (if there are any)
  if (doc.store.pendingDs) {
    updates.push(doc.store.pendingDs)
  }
  if (doc.store.pendingStructs) {
    updates.push(diffUpdateV2(doc.store.pendingStructs.update, encodedTargetStateVector))
  }
  if (updates.length > 1) {
    if (encoder.constructor === UpdateEncoderV1) {
      return mergeUpdates(updates.map((update, i) => i === 0 ? update : convertUpdateFormatV2ToV1(update)))
    } else if (encoder.constructor === UpdateEncoderV2) {
      return mergeUpdatesV2(updates)
    }
  }
  return updates[0]
}

/**
 * Write all the document as a single update message that can be applied on the remote document. If you specify the state of the remote client (`targetState`) it will
 * only write the operations that are missing.
 *
 * Use `writeStateAsUpdate` instead if you are working with lib0/encoding.js#Encoder
 *
 * @param {Doc} doc
 * @param {Uint8Array} [encodedTargetStateVector] The state of the target that receives the update. Leave empty to write all known structs
 * @return {Uint8Array<ArrayBuffer>}
 *
 * @function
 */
export const encodeStateAsUpdate = (doc, encodedTargetStateVector) => encodeStateAsUpdateV2(doc, encodedTargetStateVector, new UpdateEncoderV1())

/**
 * Read state vector from Decoder and return as Map
 *
 * @param {IdSetDecoderV1 | IdSetDecoderV2} decoder
 * @return {Map<number,number>} Maps `client` to the number next expected `clock` from that client.
 *
 * @function
 */
export const readStateVector = decoder => {
  const ss = new Map()
  const ssLength = decoding.readVarUint(decoder.restDecoder)
  for (let i = 0; i < ssLength; i++) {
    const client = decoding.readVarUint(decoder.restDecoder)
    const clock = decoding.readVarUint(decoder.restDecoder)
    ss.set(client, clock)
  }
  return ss
}

/**
 *
 * This function works similarly to `readUpdateV2`.
 *
 * @param {Array<Uint8Array<ArrayBuffer>>} updates
 * @param {typeof UpdateDecoderV1 | typeof UpdateDecoderV2} [YDecoder]
 * @param {typeof UpdateEncoderV1 | typeof UpdateEncoderV2} [YEncoder]
 * @return {Uint8Array<ArrayBuffer>}
 */
export const mergeUpdatesV2 = (updates, YDecoder = UpdateDecoderV2, YEncoder = UpdateEncoderV2) => {
  if (updates.length === 1) {
    return updates[0]
  } else if (updates.length === 0) {
    return encodeStateAsUpdateV2(new Doc(), new Uint8Array([0]), new YEncoder())
  }
  const updateDecoders = updates.map(update => new YDecoder(decoding.createDecoder(update)))
  const blocksets = updateDecoders.map(dec => readBlockSet(dec))

  const mergedBlockset = blocksets[0]
  for (let i = 1; i < blocksets.length; i++) {
    mergedBlockset.insertInto(blocksets[i])
  }
  const updateEncoder = new YEncoder()
  writeBlockSet(updateEncoder, mergedBlockset)
  const dss = updateDecoders.map(decoder => readIdSet(decoder))
  const ds = mergeIdSets(dss)
  writeIdSet(updateEncoder, ds)
  return updateEncoder.toUint8Array()
}

/**
 * @param {Array<Uint8Array<ArrayBuffer>>} updates
 * @return {Uint8Array<ArrayBuffer>}
 */
export const mergeUpdates = updates => mergeUpdatesV2(updates, UpdateDecoderV1, UpdateEncoderV1)

/**
 * @deprecated
 * @param {Uint8Array} update
 * @param {Uint8Array} sv
 * @param {typeof UpdateDecoderV1 | typeof UpdateDecoderV2} [YDecoder]
 * @param {typeof UpdateEncoderV1 | typeof UpdateEncoderV2} [YEncoder]
 */
export const diffUpdateV2 = (update, sv, YDecoder = UpdateDecoderV2, YEncoder = UpdateEncoderV2) => {
  const state = decodeStateVector(sv)
  const encoder = new YEncoder()
  const lazyStructWriter = new LazyStructWriter(encoder)
  const decoder = new YDecoder(decoding.createDecoder(update))
  const reader = new LazyStructReader(decoder, false)
  while (reader.curr) {
    const curr = reader.curr
    const currClient = curr.id.client
    const svClock = state.get(currClient) || 0
    if (reader.curr.constructor === Skip) {
      // the first written struct shouldn't be a skip
      reader.next()
      continue
    }
    if (curr.id.clock + curr.length > svClock) {
      writeStructToLazyStructWriter(lazyStructWriter, curr, math.max(svClock - curr.id.clock, 0), 0)
      reader.next()
      while (reader.curr && reader.curr.id.client === currClient) {
        writeStructToLazyStructWriter(lazyStructWriter, reader.curr, 0, 0)
        reader.next()
      }
    } else {
      // read until something new comes up
      while (reader.curr && reader.curr.id.client === currClient && reader.curr.id.clock + reader.curr.length <= svClock) {
        reader.next()
      }
    }
  }
  finishLazyStructWriting(lazyStructWriter)
  // write ds
  const ds = readIdSet(decoder)
  writeIdSet(encoder, ds)
  return encoder.toUint8Array()
}

/**
 * @deprecated
 * @todo remove this in favor of intersectupdate
 *
 * @param {Uint8Array<ArrayBuffer>} update
 * @param {Uint8Array<ArrayBuffer>} sv
 */
export const diffUpdate = (update, sv) => diffUpdateV2(update, sv, UpdateDecoderV1, UpdateEncoderV1)

/**
 * Read decodedState and return State as Map.
 *
 * @param {Uint8Array} decodedState
 * @return {Map<number,number>} Maps `client` to the number next expected `clock` from that client.
 *
 * @function
 */
// export const decodeStateVectorV2 = decodedState => readStateVector(new DSDecoderV2(decoding.createDecoder(decodedState)))

/**
 * Read decodedState and return State as Map.
 *
 * @param {Uint8Array} decodedState
 * @return {Map<number,number>} Maps `client` to the number next expected `clock` from that client.
 *
 * @function
 */
export const decodeStateVector = decodedState => readStateVector(new IdSetDecoderV1(decoding.createDecoder(decodedState)))

/**
 * @param {IdSetEncoderV1 | IdSetEncoderV2} encoder
 * @param {Map<number,number>} sv
 * @function
 */
export const writeStateVector = (encoder, sv) => {
  encoding.writeVarUint(encoder.restEncoder, sv.size)
  array.from(sv.entries()).sort((a, b) => b[0] - a[0]).forEach(([client, clock]) => {
    encoding.writeVarUint(encoder.restEncoder, client) // @todo use a special client decoder that is based on mapping
    encoding.writeVarUint(encoder.restEncoder, clock)
  })
  return encoder
}

/**
 * @param {IdSetEncoderV1 | IdSetEncoderV2} encoder
 * @param {Doc} doc
 *
 * @function
 */
export const writeDocumentStateVector = (encoder, doc) => writeStateVector(encoder, getStateVector(doc.store))

/**
 * Encode State as Uint8Array.
 *
 * @param {Doc|Map<number,number>} doc
 * @param {IdSetEncoderV1 | IdSetEncoderV2} [encoder]
 * @return {Uint8Array<ArrayBuffer>}
 *
 * @function
 */
export const encodeStateVectorV2 = (doc, encoder = new IdSetEncoderV2()) => {
  if (doc instanceof Map) {
    writeStateVector(encoder, doc)
  } else {
    writeDocumentStateVector(encoder, doc)
  }
  return encoder.toUint8Array()
}

/**
 * Encode State as Uint8Array.
 *
 * @param {Doc|Map<number,number>} doc
 * @return {Uint8Array<ArrayBuffer>}
 *
 * @function
 */
export const encodeStateVector = doc => encodeStateVectorV2(doc, new IdSetEncoderV1())

/**
 * Return the creator clientID of the missing op or define missing items and return null.
 *
 * @param {Item|CausalHole} struct
 * @param {Transaction} transaction
 * @param {StructStore} store
 * @return {null | number}
 */
const getMissing = (struct, transaction, store) => {
  if (struct.constructor !== Item && struct.constructor !== CausalHole) return null
  // we may not access these variables anymore after they have been written!
  const origin = struct.origin
  const rightOrigin = struct.rightOrigin
  const parent = struct.parent
  if (origin && (origin.clock >= store.getClock(origin.client) || store.skips.hasId(origin))) {
    return origin.client
  }
  if (rightOrigin && (rightOrigin.clock >= store.getClock(rightOrigin.client) || store.skips.hasId(rightOrigin))) {
    return rightOrigin.client
  }
  if (parent && parent.constructor === ID && (parent.clock >= store.getClock(parent.client) || store.skips.hasId(parent))) {
    return parent.client
  }
  if (struct.constructor === CausalHole) return null
  const item = /** @type {Item} */ (struct)
  // We have all missing ids, now find the items
  const originHole = origin === null ? null : store.getCausalHole(origin)
  const rightOriginHole = rightOrigin === null ? null : store.getCausalHole(rightOrigin)
  const replacesHole = store.causalHoles.intersects(item.id.client, item.id.clock, item.length)
  if (origin) {
    if (originHole === null) {
      item.left = getItemCleanEnd(transaction, store, origin)
      // copy left id to so that the original id can be gc'd
      item.origin = item.left.lastId
    }
  }
  if (rightOrigin) {
    if (rightOriginHole === null) {
      item.right = getItemCleanStart(transaction, rightOrigin)
      item.rightOrigin = item.right.id
    }
  }
  if ((item.left && item.left.constructor === GC) || (item.right && item.right.constructor === GC)) {
    item.parent = null
  } else if (originHole !== null || rightOriginHole !== null) {
    const hole = /** @type {CausalHole} */ (originHole ?? rightOriginHole)
    item.parent = resolveCausalHoleParent(transaction, store, hole)
    item.parentSub = hole.parentSub
  } else if (parent == null) {
    // only set parent if this shouldn't be garbage collected
    if (item.left && item.left.constructor === Item) {
      item.parent = item.left.parent
      item.parentSub = item.left.parentSub
    } else if (item.right && item.right.constructor === Item) {
      item.parent = item.right.parent
      item.parentSub = item.right.parentSub
    }
  } else if (parent.constructor === ID) {
    const parentItem = store.getItem(parent)
    if (parentItem.constructor === GC) {
      item.parent = null
    } else {
      item.parent = /** @type {ContentType} */ (parentItem.content).type
    }
  } else if (typeof parent === 'string') {
    item.parent = transaction.doc.get(parent)
  }
  if (originHole !== null && origin !== null) store.addCausalHoleConsumer(origin, item, 'origin')
  if (rightOriginHole !== null && rightOrigin !== null) store.addCausalHoleConsumer(rightOrigin, item, 'rightOrigin')
  if (
    (originHole !== null || rightOriginHole !== null || replacesHole) &&
    item.parent !== null && typeof item.parent !== 'string' && item.parent.constructor !== ID
  ) {
    const bounds = getVirtualInsertionBounds(transaction, store, item, /** @type {YType} */ (item.parent))
    item.left = bounds.left
    item.right = bounds.right
  }
  return null
}

/**
 * @param {Transaction} transaction
 * @param {StructStore} store
 * @param {Item} target
 * @param {YType} parent
 */
const getVirtualInsertionBounds = (transaction, store, target, parent) => {
  /**
   * @typedef {{
   *   id:ID,
   *   length:number,
   *   origin:ID|null,
   *   rightOrigin:ID|null,
   *   actual:Item|null,
   *   target:boolean,
   *   left:ShadowNode|null,
   *   right:ShadowNode|null
   * }} ShadowNode
   */
  /** @type {Array<{id:ID,length:number,origin:ID|null,rightOrigin:ID|null,actual:Item|null,target:boolean}>} */
  const ranges = []
  let current = getParentListStart(parent, target.parentSub)
  while (current !== null) {
    ranges.push({ id: current.id, length: current.length, origin: current.origin, rightOrigin: current.rightOrigin, actual: current, target: false })
    current = current.right
  }
  const parentID = normalizeCausalHoleParent(parent)
  store.clients.forEach(rawStructs => {
    const structs = /** @type {Array<GC|Item|Skip|CausalHole>} */ (/** @type {unknown} */ (rawStructs))
    for (const struct of structs) {
      if (
        struct.constructor !== CausalHole ||
        !sameCausalHoleParent(struct.parent, parentID) ||
        struct.parentSub !== target.parentSub
      ) continue
      const hole = /** @type {CausalHole} */ (struct)
      if (hole.id.client !== target.id.client || hole.id.clock + hole.length <= target.id.clock || target.id.clock + target.length <= hole.id.clock) {
        ranges.push({ id: hole.id, length: hole.length, origin: hole.origin, rightOrigin: hole.rightOrigin, actual: null, target: false })
        continue
      }
      if (hole.id.clock < target.id.clock) {
        const left = hole.slice(hole.id.clock, target.id.clock - hole.id.clock)
        ranges.push({ id: left.id, length: left.length, origin: left.origin, rightOrigin: left.rightOrigin, actual: null, target: false })
      }
      const holeEnd = hole.id.clock + hole.length
      const targetEnd = target.id.clock + target.length
      if (targetEnd < holeEnd) {
        const right = hole.slice(targetEnd, holeEnd - targetEnd)
        ranges.push({ id: right.id, length: right.length, origin: right.origin, rightOrigin: right.rightOrigin, actual: null, target: false })
      }
    }
  })
  ranges.push({ id: target.id, length: target.length, origin: target.origin, rightOrigin: target.rightOrigin, actual: null, target: true })

  /** @type {Map<number,Set<number>>} */
  const boundaries = new Map()
  /** @param {ID|null} id @param {number} offset */
  const addBoundary = (id, offset) => {
    if (id === null) return
    let clocks = boundaries.get(id.client)
    if (clocks === undefined) {
      clocks = new Set()
      boundaries.set(id.client, clocks)
    }
    clocks.add(id.clock + offset)
  }
  for (const range of ranges) {
    addBoundary(range.origin, 1)
    addBoundary(range.rightOrigin, 0)
  }
  store.causalHoleConsumers.forEach((entries, client) => {
    for (const entry of entries) addBoundary(createID(client, entry.clock), entry.side === 'origin' ? 1 : 0)
  })

  /** @type {Array<ShadowNode>} */
  const nodes = []
  for (const range of ranges) {
    const end = range.id.clock + range.length
    const cuts = array.from(boundaries.get(range.id.client) ?? [])
      .filter(clock => range.id.clock < clock && clock < end)
      .sort((left, right) => left - right)
    let clock = range.id.clock
    for (const cut of cuts.concat(end)) {
      nodes.push({
        id: createID(range.id.client, clock),
        length: cut - clock,
        origin: clock === range.id.clock ? range.origin : createID(range.id.client, clock - 1),
        rightOrigin: range.rightOrigin,
        actual: range.actual,
        target: range.target,
        left: null,
        right: null
      })
      clock = cut
    }
  }

  /** @type {Map<number,Array<ShadowNode>>} */
  const nodesByClient = new Map()
  for (const node of nodes) {
    const clientNodes = nodesByClient.get(node.id.client) ?? []
    clientNodes.push(node)
    nodesByClient.set(node.id.client, clientNodes)
  }
  nodesByClient.forEach(clientNodes => clientNodes.sort((left, right) => left.id.clock - right.id.clock))
  /** @param {ID} id */
  const getNode = id => {
    const clientNodes = nodesByClient.get(id.client)
    if (clientNodes === undefined) return null
    let left = 0
    let right = clientNodes.length - 1
    while (left <= right) {
      const middle = (left + right) >>> 1
      const node = clientNodes[middle]
      if (id.clock < node.id.clock) right = middle - 1
      else if (id.clock >= node.id.clock + node.length) left = middle + 1
      else return node
    }
    return null
  }

  /** @type {Map<ShadowNode,number>} */
  const indegree = new Map()
  /** @type {Map<ShadowNode,Array<ShadowNode>>} */
  const dependents = new Map()
  for (const node of nodes) {
    const dependencies = new Set()
    for (const anchor of [node.origin, node.rightOrigin]) {
      if (anchor === null) continue
      const dependency = getNode(anchor)
      if (dependency === null) throw new Error('Missing virtual causal anchor')
      if (dependency !== node) dependencies.add(dependency)
    }
    indegree.set(node, dependencies.size)
    dependencies.forEach(dependency => {
      const list = dependents.get(dependency) ?? []
      list.push(node)
      dependents.set(dependency, list)
    })
  }
  const ready = nodes.filter(node => indegree.get(node) === 0)
  ready.sort((left, right) => left.id.client - right.id.client || left.id.clock - right.id.clock)
  /** @type {ShadowNode|null} */
  let start = null
  let integrated = 0
  while (ready.length > 0) {
    const node = /** @type {ShadowNode} */ (ready.pop())
    let left = node.origin === null ? null : getNode(node.origin)
    const right = node.rightOrigin === null ? null : getNode(node.rightOrigin)
    if ((!left && (!right || right.left !== null)) || (left && left.right !== right)) {
      let scan = left === null ? start : left.right
      const conflictingItems = new Set()
      const itemsBeforeOrigin = new Set()
      while (scan !== null && scan !== right) {
        itemsBeforeOrigin.add(scan)
        conflictingItems.add(scan)
        if (compareIDs(node.origin, scan.origin)) {
          if (scan.id.client < node.id.client) {
            left = scan
            conflictingItems.clear()
          } else if (compareIDs(node.rightOrigin, scan.rightOrigin)) {
            break
          }
        } else if (scan.origin !== null) {
          const scanOrigin = getNode(scan.origin)
          if (scanOrigin !== null && itemsBeforeOrigin.has(scanOrigin)) {
            if (!conflictingItems.has(scanOrigin)) {
              left = scan
              conflictingItems.clear()
            }
          } else {
            break
          }
        } else {
          break
        }
        scan = scan.right
      }
    }
    node.left = left
    if (left === null) {
      node.right = start
      start = node
    } else {
      node.right = left.right
      left.right = node
    }
    if (node.right !== null) node.right.left = node
    integrated++
    for (const dependent of dependents.get(node) ?? []) {
      const remaining = /** @type {number} */ (indegree.get(dependent)) - 1
      indegree.set(dependent, remaining)
      if (remaining === 0) ready.push(dependent)
    }
  }
  if (integrated !== nodes.length) throw new Error('Cyclic virtual causal metadata')
  const targets = nodes.filter(node => node.target)
  if (targets.length !== 1) throw new Error('Sparse replacement must split at virtual consumers')
  let shadowLeft = targets[0].left
  while (shadowLeft !== null && shadowLeft.actual === null) shadowLeft = shadowLeft.left
  let shadowRight = targets[0].right
  while (shadowRight !== null && shadowRight.actual === null) shadowRight = shadowRight.right
  return {
    left: shadowLeft === null ? null : getItemCleanEnd(transaction, store, createID(shadowLeft.id.client, shadowLeft.id.clock + shadowLeft.length - 1)),
    right: shadowRight === null ? null : getItemCleanStart(transaction, createID(shadowRight.id.client, shadowRight.id.clock))
  }
}

/** @param {YType} parent @param {string|null} parentSub */
const getParentListStart = (parent, parentSub) => {
  if (parentSub === null) return parent._start
  let item = parent._map.get(parentSub) ?? null
  while (item !== null && item.left !== null) item = item.left
  return item
}

/**
 * @param {Transaction} transaction
 * @param {StructStore} store
 * @param {CausalHole} hole
 * @return {YType}
 */
const resolveCausalHoleParent = (transaction, store, hole) => {
  if (typeof hole.parent === 'string') return transaction.doc.get(hole.parent)
  if (store.getCausalHole(hole.parent) !== null) throw new Error('Causal hole parent is not materialized')
  const parentItem = store.getItem(hole.parent)
  if (parentItem.constructor !== Item || !(parentItem.content instanceof ContentType)) throw new Error('Causal hole parent is not a materialized type')
  return parentItem.content.type
}

/**
 * @param {Uint8Array} update
 * @param {import('./Doc.js').DocOpts} opts
 */
export const createDocFromUpdate = (update, opts = {}) => {
  const ydoc = new Doc(opts)
  applyUpdate(ydoc, update)
  return ydoc
}

/**
 * @param {Uint8Array} update
 * @param {import('./Doc.js').DocOpts} opts
 */
export const createDocFromUpdateV2 = (update, opts = {}) => {
  const ydoc = new Doc(opts)
  applyUpdateV2(ydoc, update)
  return ydoc
}

/**
 * @param {Doc} ydoc
 * @param {import('./Doc.js').DocOpts} [opts]
 */
export const cloneDoc = (ydoc, opts) => {
  const clone = new Doc(opts)
  applyUpdate(clone, encodeStateAsUpdate(ydoc))
  return clone
}
